### ISSUE TITLE
Move all image files to images/

### ISSUE THREAD

**Issue by russHyde** [r4ds/bookclub-mshiny#10]
To keep the repo neat, we should limit how many directories/files are added at the top level.

Suggest adding image files to
`./images/<chapter-number>/<image-name>.[jpeg|png|...]`

**Comment by aditya28sarin** [comment]
can you assign me this issue?

**Comment by russHyde** [comment]
No. Someone is already working on it in #14

**Comment by aditya28sarin** [comment]
okay thanks sure
