### ISSUE TITLE
Wrong hyperlink for cohort 4 youtube playlist

### ISSUE THREAD

**Issue by lgibson7** [r4ds/bookclub-mshiny#109]
The current hyperlink goes to a playlist for R Packages. This is the [correct playlist](https://youtube.com/playlist?list=PL3x6DOfs2NGgi_CE58EIdQT69b-H5g6ig&si=Y4bNZn1wHkt5V4Oz)

**Comment by jonthegeek** [comment]
Can you submit a pull request to fix it? Thanks!

**Comment by lgibson7** [comment]
Hey @jonthegeek. Thanks for doing the PR for me. It looks like the issue wasn't auto-closed so I'll do it manually. Cheers.
