### ISSUE TITLE
Fix 404 for shiny cheatsheet in "Your first shiny app" Chapter

### ISSUE THREAD

**Issue by russHyde** [r4ds/bookclub-mshiny#16]
https://r4ds.github.io/bookclub-mshiny/shiny-resources.html

There is a link to the shiny cheatsheet at the top of the page, but the sheet isn't visible and a 404 message shows up

**Comment by collinberke** [comment]
I think I addressed this in pull request #66 . Formatting isn't the greatest, though. Please verify if this has been fixed. Thanks.

**Comment by russHyde** [comment]
THanks
