### ISSUE TITLE
Github / Git notes in the README could be clearer

### ISSUE THREAD

**Issue by russHyde** [r4ds/bookclub-mshiny#28]
Hi @tanho63 / @jonthegeek .
I've just helped @Fgazzelloni start her first bookclub-mshiny PR.
The notes re git in the README are a bit confusing.

There is a link to a video that Tan put together (the font in the video is rather small and, since the video is tied to the command line, may not present the best git workflow for an rstudio user).
Maybe the README ought to have a link to the appropriate chapters of happygitwithr as well, and an indication that the user can follow the instructions in the video but should be forking / cloning the bookclub-mshiny repository (rather than the example repo - bookclub-template - used in the video)

**Comment by tanho63** [comment]
I don't have an issue with someone rerecording the git introduction with an rstudio flow (i'm probably not the best person for it)

**Comment by collinberke** [comment]
We tried to address this in Cohort 2 with a 'Get up and running with `git`' discussion at the start of the book club. You can see these materials in b16861e26a51154c75aad8c6862190d4eb26feaa accepted in pull request #66. I don't think this fully resolves this issue, but it's a start. 

I'm open to thinking about and creating some more material to resolve this issue, though I'm far from a `git` foo master. It will come down to clarifying what skills are needed to contribute to the book club's materials. From getting it set up to learning the basic workflows, `git` can be overwhelming, especially if you've never worked with version control before. Some material overviewing the basic workflows might help. 

As for materials on using `bookdown`, I'm not the right person for this. I'm still learning.

**Comment by jonthegeek** [comment]
I think I clarified it with the usethis workflow.
